spring:
  application:
    name: spring-batch-data-manager
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./test
    driverClassName: org.h2.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    configs:
      input-file-path: data/dataSource.txt
      job-name: importTransactionsJob
      delimiter: "|"
      chunk-size: 10

file:
  input: data/dataSource.txt

