spring:
  application:
    name: spring-batch-data-manager
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: sa
file:
  input: data/dataSource.txt

